apiVersion: v1
kind: ServiceAccount
metadata:
  name: curl
---  
apiVersion: v1
kind: Pod
metadata:
  name: curl
  labels:
    app: curl
  annotations:
    "consul.hashicorp.com/connect-inject": "true"
    "consul.hashicorp.com/connect-service-upstreams": "web:9091"
spec:
  serviceAccountName: curl
  containers:
    - name: curl
      image: docker.io/tutum/curl
      ports:
        #- name: fakeport
        #  containerPort: 9090
        #  protocol: TCP
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do sleep 30; done;" ]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: web  
---
apiVersion: v1
kind: Pod
metadata:
  name: web      
  labels:
    app: web
  annotations:
    "consul.hashicorp.com/connect-inject": "true"
spec:
  serviceAccountName: web
  containers:
    - name: web
      image: docker.io/httpd
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: web
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80